// B1 claim account copy. Passkey is the one MVP unlock path: no email, no phone,
// no SSO. A screen here is a title plus its controls; no explainer prose.
export const COPY = {
  title: "Create your account",
  loginTitle: "Log in",
  usePasskeyLogin: "Log in with a passkey",
  otherWaysLabel: "Other ways to log in",
  recoverLabel: "Recovery phrase",
  recoverCta: "Log in",
  recoverPwNameLabel: "Handle",
  recoverPwPasswordLabel: "Password",
  recoverPwCta: "Log in",
  switchToCreate: "New here? Create an account",
  switchToLogin: "Already have an account? Log in",
  nameLabel: "What should we call you?",
  nameHint: "Only you see this.",
  shuffleLabel: "Shuffle a name",
  nameTooShort: "At least 3 characters.",
  cta: "Continue",
} as const;
